{
    'name': 'AutomatedSEO',
    'version': '1.0',
    'category': 'Extra Tools',
    'license':'LGPL-3',
    'summary': 'A simple QWeb demo',
    'description': """This module demonstrates a basic QWeb template in Odoo 16.""",
    'author': 'Hetul Patel',
    'depends': ['base',"web", 'website'],
    'data': [
        # 'security/security.xml',
        'security/ir.model.access.csv',
        "views/views.xml",
        "views/php_mapper_view.xml",
        "views/snippets/steps/s_steps_bg_white.xml",
        "views/snippets/steps/s_steps_bg_gray.xml",
        "views/snippets/footer/s_footer_slider_bg_gray.xml",
        "views/snippets/header/s_header.xml",
        "views/snippets/footer/s_footer_slider_bg_white.xml",
        "views/snippets/footer/s_footer_bg_gray.xml",
        "views/snippets/footer/s_footer_bg_white.xml",
        "views/snippets/counting_sec/s_counting_sec.xml",
        "views/snippets/tech_stack/s_technical_stack_bg_gray.xml",
        "views/snippets/tech_stack/s_technical_stack_bg_white.xml",
        "views/snippets/trusted/s_trusted_bg_gray.xml",
        "views/snippets/trusted/s_trusted_bg_white.xml",
        "views/snippets/useful_links/s_useful_links_bg_gray.xml",
        "views/snippets/useful_links/s_useful_links_bg_white.xml",
        "views/snippets/faq/s_faq_bg_white.xml",
        "views/snippets/faq/s_faq_with_button_bg_white.xml",
        "views/snippets/side_image/s_side_image_bg_gray.xml",
        "views/snippets/side_image/s_side_image_bg_white.xml",
        "views/snippets/side_image/s_left_side_image_bg_gray.xml",
        "views/snippets/side_image/s_left_side_image_bg_white.xml",
        "views/snippets/side_image/s_side_img_list_bg_white.xml",
        "views/snippets/side_image/s_side_img_list_bg_gray.xml",
        "views/snippets/side_image/s_right_side_img_list_bg_gray.xml",
        "views/snippets/side_image/s_right_side_img_list_bg_white.xml",
        "views/snippets/side_image/s_side_img_cards_bg_gray.xml",
        "views/snippets/side_image/s_side_img_cards_bg_white.xml",
        "views/snippets/side_image/s_side_video_bg_white.xml",
        "views/snippets/side_image/s_side_video_bg_gray.xml",
        "views/snippets/cta/s_dark_cta_bg_white.xml",
        "views/snippets/cta/s_dark_cta_bg_gray.xml",
        "views/snippets/banner/s_banner_health_bg_gray.xml",
        "views/snippets/banner/s_banner_side_image_with_2_button.xml",
        "views/snippets/banner/s_banner_side_image_with_2_button_and_bg.xml",
        "views/snippets/banner/s_banner_side_image_with_button.xml",
        "views/snippets/banner/s_banner_side_image_with_form_and_bg.xml",
        "views/snippets/banner/s_banner_side_matrix_with_button_and_icon.xml",
        "views/snippets/banner/s_banner_side_matrix_with_button.xml",
        "views/snippets/services/s_banner_cards_bg_white.xml",
        "views/snippets/services/s_banner_cards_bg_gray.xml",
        "views/snippets/services/s_hire_developer_bg_white.xml",
        "views/snippets/services/s_hire_developer_bg_gray.xml",
        "views/snippets/services/s_hire_expertise_developer_bg_white.xml",
        "views/snippets/cards/s_card_with_icon_bg_gray.xml",
        "views/snippets/cards/s_card_with_icon_bg_white.xml",
        "views/snippets/cards/s_card_with_list_bg_gray.xml",
        "views/snippets/cards/s_card_with_list_bg_white.xml",
        "views/snippets/cards/s_card_with_list_and_button_bg_gray.xml",
        "views/snippets/cards/s_card_with_list_and_button_bg_white.xml",
        "views/snippets/cards/s_card_2_box_list_bg_white.xml",
        "views/snippets/cards/s_card_2_box_list_bg_gray.xml",
        "views/snippets/cards/s_card_with_icon_grid_2_bg_white.xml",
        "views/snippets/cards/s_card_with_button_bg_white.xml",
        "views/snippets/hiring_model/s_hiring_model_bg_white.xml",
        "views/snippets/hiring_model/s_hiring_model_bg_gray.xml",
        "views/snippets/leadership/s_leadership_bg_gray.xml",
        "views/snippets/leadership/s_leadership_bg_white.xml",
        "views/snippets/internal_linking/s_internal_linking_box_with_arrow_bg_gray.xml",
        "views/snippets/internal_linking/s_internal_linking_box_with_arrow_bg_white.xml",
        "views/snippets/internal_linking/s_internal_linking_list_bg_white.xml",
        "views/snippets/internal_linking/s_internal_linking_list_bg_gray.xml",
        "views/snippets/industries/s_industries_gray.xml",
        "views/snippets/industries/s_industries_white.xml",
        "views/snippets/video_section/s_solution_health_bg_white.xml",
        "views/snippets/video_section/s_solution_health_bg_gray.xml",
        "views/snippets/testimonials/s_client_feedback_2_bg_white.xml",
        "views/snippets/testimonials/s_client_feedback_2_bg_gray.xml",
        "views/snippets/testimonials/s_client_feedback_bg_white.xml",
        "views/snippets/testimonials/s_client_feedback_bg_gray.xml",
        "views/snippets/image_section/s_hire_expert_bg_white.xml",
        "views/snippets/image_section/s_hire_expert_bg_gray.xml",
        "views/snippets/tab/s_horizontal_tab_bg_white.xml",
        "views/snippets/tab/s_vertical_tab_bg_gray.xml",
        "views/snippets/tab/s_vertical_tab_bg_white.xml",
        "views/snippets/tab/s_horizontal_tab_bg_gray.xml",
        "views/snippets/tab/s_hire_dedicated_dev_bg_white.xml",
        "views/snippets/tab/s_hire_dedicated_dev_bg_gray.xml",
        "views/snippets/sub_cards/s_card.xml",
        "views/snippets/case_study/s_case_study_bg_gray.xml",
        "views/snippets/case_study/s_case_study_bg_white.xml",
        "views/snippets/slider/s_combination_slider_bg_white.xml",
        "views/snippets/slider/s_combination_slider_bg_gray.xml",
        "views/snippets/developer/s_profile_bg_gray.xml",
        "views/snippets/developer/s_profile_bg_white.xml",
        "views/snippets/form/s_banner_form.xml",
        "views/snippets/form/s_footer_form.xml",
        "views/snippets/form/s_single_form.xml",
        "views/snippets/form/s_form_with_price_gray.xml",
        "views/snippets/form/s_form_with_price_orange.xml",
        "views/snippets/fortune/s_fortune.xml",

        "views/snippets/trusted_parties/s_trusted_parties_bg_gray.xml",
        "views/snippets/trusted_parties/s_trusted_parties_bg_white.xml",
        'views/snippets/snippets.xml',

        # "views/snippets/s_angular_offer.xml",
        # "views/snippets/page/s_developer_pricing_bg_white.xml",
        # "views/snippets/s_angular_header.xml",
        # "views/snippets/s_angular_heir_tag.xml",
        # "views/snippets/s_about_angular_team.xml",
        # "views/snippets/s_angular_hire_steps.xml",
        # "views/snippets/s_angular_choose_developer.xml",
        # "views/snippets/s_angular_story.xml",
        # "views/snippets/s_offer.xml",
        # "views/snippets/s_hire_angular_dev.xml",
        # "views/snippets/s_angular_offer.xml",
        # "views/snippets/s_schedule_interview.xml",
        # "views/snippets/page/s_angular_dev_expertise_bg_white.xml",
        # "views/snippets/s_counting_sec.xml",
        # "views/snippets/s_banner.xml",
        # "views/snippets/s_full_stack_angular_type.xml",
        # "views/snippets/s_useful_links.xml",
        # "views/snippets/s_frequently_ask_questions.xml",
        # "views/snippets/s_footer.xml",
        # "views/snippets/s_help.xml",

    ],
    'assets': {
        'web.assets_frontend': [
            'automated_seo/static/src/css/casestudy.css',
            'automated_seo/static/src/css/faq.css',
            'automated_seo/static/src/css/footer-slider.css',
            'automated_seo/static/src/css/style.css',
            'automated_seo/static/src/css/tech-stack.css',
            'automated_seo/static/src/css/header.css',
            'automated_seo/static/src/css/footer.css',
            'automated_seo/static/src/css/form.css',
            'automated_seo/static/src/css/hiring-modal-table.css',
            'automated_seo/static/src/css/indu-sec.css',
            'automated_seo/static/src/css/tab-sec.css',
            'automated_seo/static/src/js/main.js',
        ],
        'website.assets_wysiwyg': [
            ('include', 'web._assets_helpers'),
            'automated_seo/static/src/js/angular_offer.js'
        ],
    },
}
